(function(root){
  const view={token:'',items:[],editing:null,error:'',busy:false,
    render(area){
      const esc=biasApi.esc,r=this.editing || {act:'',title:'',date:biasCore.koreaDate(),type:'Single',genres:[],description:'',sourceUrl:'',pipelineStep:1,state:'draft'};
      if(!this.token){area.innerHTML=`<div class="curation-box"><span class="pill pill-accent">Öffentliche Redaktion</span><h3>Gemeinsamen Radar pflegen</h3><p class="box-sub">Öffentliche Einträge werden auf dem Server gespeichert. Zum Bearbeiten benötigst du den Redaktionszugang.</p><form id="editorial-login" class="inline-form"><input class="text-input" id="editorial-token" type="password" autocomplete="off" aria-label="Redaktionsschlüssel" placeholder="Redaktionsschlüssel" required><button class="btn btn-accent">Redaktion öffnen</button></form>${this.error?`<p role="alert" class="inline-error">${esc(this.error)}</p>`:''}</div>`;area.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=area.querySelector('input'),button=area.querySelector('button');button.disabled=true;try{const token=input.value;const result=await biasApi.request('api/editorial/releases',{headers:{Authorization:'Bearer '+token}});this.token=token;this.items=result.items;this.error='';this.render(area);}catch(err){this.error=err.message;this.render(area);}};return;}
      area.innerHTML=`<div class="connection-heading"><h2>Öffentliche Releases</h2><button class="btn btn-ghost" id="editorial-logout">Redaktion schließen</button></div><div class="curation-split-grid"><div class="curation-box"><h3>${this.editing?'Eintrag bearbeiten':'Neuen Eintrag anlegen'}</h3><form id="editorial-form" class="studio-form">
        <div class="form-grid-2"><div class="form-group"><label for="ed-act" class="form-label">Künstler</label><input id="ed-act" class="text-input" value="${esc(r.act)}" maxlength="120" required></div><div class="form-group"><label for="ed-title" class="form-label">Titel</label><input id="ed-title" class="text-input" value="${esc(r.title)}" maxlength="200" required></div></div>
        <div class="form-grid-2"><div class="form-group"><label for="ed-date" class="form-label">Veröffentlichung</label><input id="ed-date" type="date" class="text-input" value="${esc(r.date)}" required></div><div class="form-group"><label for="ed-type" class="form-label">Format</label><select id="ed-type" class="select-input">${['Single','Album','EP','OST','Repackage'].map(t=>`<option ${r.type===t?'selected':''}>${t}</option>`).join('')}</select></div></div>
        <label for="ed-source" class="form-label">Quelle zur Ankündigung</label><input id="ed-source" type="url" class="text-input" value="${esc(r.sourceUrl)}" placeholder="https://…" required>
        <label for="ed-genres" class="form-label">Genres, durch Komma getrennt</label><input id="ed-genres" class="text-input" value="${esc(r.genres.join(', '))}">
        <label for="ed-description" class="form-label">Beschreibung</label><textarea id="ed-description" class="text-input" maxlength="2000">${esc(r.description)}</textarea>
        <div class="form-grid-2"><div class="form-group"><label for="ed-phase" class="form-label">Release-Phase</label><select id="ed-phase" class="select-input">${['Angekündigt','Konzept-Fotos','MV-Teaser','Erschienen'].map((n,i)=>`<option value="${i+1}" ${r.pipelineStep===i+1?'selected':''}>${n}</option>`).join('')}</select></div><div class="form-group"><label for="ed-state" class="form-label">Sichtbarkeit</label><select id="ed-state" class="select-input"><option value="draft" ${r.state==='draft'?'selected':''}>Entwurf – nur Redaktion</option><option value="published" ${r.state==='published'?'selected':''}>Öffentlich im Radar</option></select></div></div>
        <div class="import-actions"><button class="btn btn-accent" ${this.busy?'disabled':''}>${this.busy?'Wird gespeichert …':'Eintrag speichern'}</button><button type="button" id="editorial-cancel" class="btn btn-ghost">Zurücksetzen</button></div><p class="section-note">Ein öffentlicher Eintrag wird nach dem Speichern für alle Besucher im Radar sichtbar.</p></form></div>
        <div class="curation-box"><div class="connection-heading"><h3>${this.items.length} Einträge</h3><button class="btn btn-ghost btn-sm" id="editorial-refresh">Neu laden</button></div>${this.items.map(item=>`<article class="custom-cb-card"><span class="pill ${item.state==='published'?'pill-accent':'pill-muted'}">${item.state==='published'?'Öffentlich':'Entwurf'}</span><h4>${esc(item.act)} — ${esc(item.title)}</h4><p class="section-note">${esc(item.date)} · Version ${item.version}</p><div class="import-actions"><button class="btn btn-ghost btn-sm" data-ed-edit="${item.id}">Bearbeiten</button><button class="btn btn-ghost btn-sm" data-ed-delete="${item.id}">Löschen</button><a class="btn btn-ghost btn-sm" href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">Quelle ↗</a></div></article>`).join('') || '<p class="section-note">Noch keine Einträge vorhanden.</p>'}</div></div>${this.error?`<p role="alert" class="inline-error">${esc(this.error)}</p>`:''}`;
      area.querySelector('#editorial-logout').onclick=()=>{this.token='';this.items=[];this.editing=null;this.error='';this.render(area);};
      area.querySelector('#editorial-cancel').onclick=()=>{this.editing=null;this.error='';this.render(area);};
      area.querySelector('#editorial-refresh').onclick=()=>this.reload(area);
      area.querySelectorAll('[data-ed-edit]').forEach(button=>button.onclick=()=>{this.editing=this.items.find(i=>i.id===button.dataset.edEdit);this.error='';this.render(area);area.querySelector('#ed-act').focus();});
      area.querySelectorAll('[data-ed-delete]').forEach(button=>button.onclick=()=>{const item=this.items.find(i=>i.id===button.dataset.edDelete);const modal=biasModals.createModalContainer(`<div class="modal-header"><h2>Release löschen?</h2><p>${esc(item.act)} — ${esc(item.title)} wird dauerhaft aus der öffentlichen Redaktion entfernt.</p></div><div class="modal-footer"><button class="btn btn-ghost" data-action="close-modal">Behalten</button><button class="btn btn-accent" id="ed-confirm-delete">Löschen</button></div>`);modal.querySelector('#ed-confirm-delete').onclick=async e=>{e.target.disabled=true;try{await biasApi.request(`api/editorial/releases/${item.id}?version=${item.version}`,{method:'DELETE',headers:{Authorization:'Bearer '+this.token}});biasModals.closeCurrentModal();this.editing=null;await this.reload(area);}catch(err){biasModals.closeCurrentModal();this.error=err.message;this.render(area);}};});
      area.querySelector('#editorial-form').onsubmit=async e=>{e.preventDefault();if(this.busy)return;const get=id=>area.querySelector('#ed-'+id).value;const payload={...(this.editing || {}),act:get('act'),title:get('title'),date:get('date'),type:get('type'),sourceUrl:get('source'),description:get('description'),genres:get('genres').split(',').map(g=>g.trim()).filter(Boolean),pipelineStep:Number(get('phase')),state:get('state')};this.busy=true;const submit=e.target.querySelector('button');submit.disabled=true;try{await biasApi.request('api/editorial/releases',{method:'POST',headers:{Authorization:'Bearer '+this.token,'Content-Type':'application/json'},body:JSON.stringify(payload)});this.editing=null;this.error='';await this.reload(area);biasApp.showToast(payload.state==='published'?'Release öffentlich gespeichert.':'Entwurf gespeichert.');}catch(err){this.error=err.message;let alert=area.querySelector('[role="alert"]');if(!alert){alert=document.createElement('p');alert.className='inline-error';alert.setAttribute('role','alert');area.appendChild(alert);}alert.textContent=err.message;}finally{this.busy=false;submit.disabled=false;}};
    },
    async reload(area){try{const result=await biasApi.request('api/editorial/releases',{headers:{Authorization:'Bearer '+this.token}});this.items=result.items;this.error='';this.busy=false;if(area.isConnected)this.render(area);biasCalendarView.releaseLoaded=false;}catch(err){this.error=err.message;if(area.isConnected)this.render(area);}}
  };
  root.biasEditorial=view;
})(window);
