(function(root){
 const {esc,chartEmpty}=biasUI;
 root.biasHomeView={render(container){
  const daily=biasCore.daily();
  container.innerHTML=`<div class="view-home">
   <section class="hero-section landing-hero"><p class="hero-eyebrow">Koreanische Musik. Über den Bias hinaus.</p><h1 class="hero-headline">Deine Hördaten,<br><span>koreanisch kuratiert.</span></h1><p class="hero-desc">Entdecke Releases, verstehe Credits und finde heraus,<br class="desktop-break"> wie viel Korea in deinem Hörverlauf steckt.</p><div class="hero-actions"><a class="btn btn-accent btn-lg" href="#stats">Korea-Mix entdecken →</a><button class="text-action" id="how-link">So funktioniert’s ↓</button></div><p class="section-note">Öffentliches Last.fm- oder ListenBrainz-Profil ansehen. Kein Spotify-Pflichtlogin.</p></section>
   <section class="landing-charts" aria-label="Zwei Perspektiven auf Musik"><article class="chart-preview"><div class="sec-head"><h2>Community Charts</h2><span class="mono">TOP 10</span></div>${chartEmpty('community')}<a href="#charts/community" class="btn btn-ghost">Zur Methodik →</a></article><article class="chart-preview"><div class="sec-head"><h2>Korea Charts</h2><span class="mono">TOP 10</span></div>${chartEmpty('korea')}<a href="#charts/korea" class="btn btn-ghost">Quellen entdecken →</a></article></section>
   <section class="landing-charts"><article class="discovery-feature"><p class="hero-eyebrow">Dein nächster Release</p><h2>Vorfreude hat einen Platz.</h2><p>Ankündigungen und Veröffentlichungen als kompakte Agenda oder im Monatskalender. Merke dir, was dich interessiert.</p><a class="btn btn-ghost" href="#kalender">Zum Radar →</a></article><article class="discovery-feature"><p class="hero-eyebrow">Daily #${daily.dayNumber} · 00:00 KST</p><h2>Drei Rätsel. Dein Musikwissen.</h2><p>Release, Artist und Credits: sechs Versuche pro Modus, jeden Tag ein neues Set.</p><a class="btn btn-ghost" href="#game">Heute mitraten →</a></article></section>
   <section id="how-it-works" class="how-section" tabindex="-1"><p class="hero-eyebrow">So funktioniert bias.fm</p><h2>Musik entdecken. Zusammenhänge verstehen.</h2><div class="how-grid"><article><span>01</span><h3>Entdecken</h3><p>Idol, Indie, R&B und Hiphop – mit Artists und den Menschen hinter den Credits.</p><a href="#catalog">Im Katalog stöbern →</a></article><article><span>02</span><h3>Einordnen</h3><p>Eine öffentliche Hörhistorie laden. Erkannte Künstler und nicht zugeordnete Plays bleiben klar getrennt.</p></article><article><span>03</span><h3>Behalten</h3><p>Favoriten, Termine und dein Musikprofil auf diesem Gerät speichern. Gehört wird bei deinem Streamingdienst.</p><a href="#profile">Dein Profil gestalten →</a></article></div></section></div>`;
  container.querySelector('#how-link').onclick=()=>{const section=container.querySelector('#how-it-works');section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});section.focus({preventScroll:true});};
 }};
})(window);
