(function(root){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const view={activeTab:'impressum',operator:null,
    render(container){container.innerHTML=`<div class="view-legal"><div class="view-header"><div><h1 class="view-title">Kontakt &amp; Datenschutz</h1><p class="view-subtitle">Wer bias.fm betreibt und wie die Funktionen mit deinen Daten umgehen.</p></div></div><div class="source-tabs">${[['impressum','Betreiber'],['datenschutz','Datenschutzhinweise'],['tdddg','Lokaler Speicher'],['urheberrecht','Musik & Quellen']].map(([id,name])=>`<button class="source-tab ${id===this.activeTab?'is-active':''}" data-legal-tab="${id}">${name}</button>`).join('')}</div><div class="settings-card legal-content" id="legal-content-area"></div></div>`;container.querySelectorAll('[data-legal-tab]').forEach(button=>button.onclick=()=>{this.activeTab=button.dataset.legalTab;this.render(container);});this.renderTab();if(!this.operator&&typeof fetch==='function')this.loadOperator();},
    async loadOperator(){try{const config=await biasApi.request('api/config');this.operator=config.operator;if(biasApp.currentRoute==='legal')this.renderTab();}catch{this.operator={};if(biasApp.currentRoute==='legal')this.renderTab();}},
    renderTab(){const area=document.getElementById('legal-content-area');if(!area)return;
      if(this.activeTab==='impressum'){const o=this.operator || {};area.innerHTML=`<h2>Betreiberangaben</h2>${o.name&&o.address&&o.email?`<div class="legal-section"><h3>${esc(o.name)}</h3><p style="white-space:pre-line">${esc(o.address)}</p><p>${esc(o.email)}</p></div>`:'<p class="inline-error">Die tatsächlichen Betreiber- und Kontaktangaben sind noch zu ergänzen. Diese Seite ist vor einer öffentlichen Inbetriebnahme zu vervollständigen.</p>'}`;}
      else if(this.activeTab==='datenschutz')area.innerHTML=`<h2>So werden Daten verwendet</h2><div class="legal-section"><h3>Deine persönliche Sammlung</h3><p>Profil, Akzentfarbe, Favoriten, persönliche Termine, Suchaliase, Spotify-Links und Rätselstände werden in diesem Browser gespeichert. Diese Inhalte werden nicht automatisch mit anderen Geräten synchronisiert.</p></div><div class="legal-section"><h3>Hörstatistik</h3><p>Ein Import übermittelt den eingegebenen öffentlichen Nutzernamen an den ausgewählten Dienst Last.fm oder ListenBrainz. Der Server hält das Ergebnis bis zu fünf Minuten im Arbeitsspeicher bereit; die Oberfläche zeigt es während der Sitzung. Unbekannte Künstler bleiben nicht zugeordnet.</p></div><div class="legal-section"><h3>Spotify-Verbindung</h3><p>Wenn du Spotify verbindest, erfolgt die Anmeldung bei Spotify. Zugangstokens liegen ausschließlich im Arbeitsspeicher des Servers. Ein notwendiges HttpOnly-Sitzungscookie ordnet die Verbindung diesem Browser zu und läuft spätestens nach sieben Tagen ab. Nach einem Serverneustart ist eine erneute Anmeldung erforderlich. „Verbindung trennen“ löscht diese Sitzung; eine Spotify-Freigabe kannst du zusätzlich in deinem Spotify-Konto widerrufen.</p></div><div class="legal-section"><h3>Öffentliche Redaktion und externe Inhalte</h3><p>Veröffentlichte Redaktionseinträge sind für alle Besucher sichtbar und liegen dauerhaft im Datenspeicher des Servers. Entwürfe sind nur mit Redaktionszugang lesbar. MusicBrainz liefert Release-Metadaten. Schriftarten können von Google Fonts und Playlist-Bilder nach Spotify-Verknüpfung von Spotify geladen werden; dabei erhält der jeweilige Anbieter technisch notwendige Verbindungsdaten. Externe Musiklinks öffnen den ausgewählten Dienst.</p></div><p class="section-note">Diese Beschreibung dokumentiert das aktuelle Verhalten der Anwendung. Die vollständigen Angaben des verantwortlichen Betreibers müssen vor dem öffentlichen Betrieb ergänzt werden.</p>`;
      else if(this.activeTab==='tdddg'){area.innerHTML=`<h2>Deine Daten in diesem Browser</h2><p>Du kannst deine persönlichen bias.fm-Einstellungen hier entfernen. Andere Websites und öffentliche Redaktionseinträge bleiben davon unberührt.</p><div class="import-actions"><button class="btn btn-ghost" id="clear-bias-data">Persönliche bias.fm-Daten löschen</button></div>`;area.querySelector('button').onclick=()=>{const modal=biasModals.createModalContainer('<div class="modal-header"><h2>Persönliche Daten löschen?</h2><p>Profil, Favoriten, persönliche Termine, Playlist-Links und Rätselstände werden aus diesem Browser entfernt. Eine aktive Spotify-Verbindung wird getrennt.</p></div><div class="modal-footer"><button class="btn btn-ghost" data-action="close-modal">Behalten</button><button class="btn btn-accent" id="confirm-local-reset">Daten löschen</button></div>');modal.querySelector('#confirm-local-reset').onclick=async e=>{e.target.disabled=true;try{if(typeof fetch==='function')await biasApi.request('api/spotify/disconnect',{method:'POST'});Object.keys(localStorage).filter(key=>key.startsWith('biasfm_')).forEach(key=>localStorage.removeItem(key));location.reload();}catch(err){e.target.disabled=false;biasApp.showToast('Löschen nicht abgeschlossen: '+err.message);}};};}
      else area.innerHTML='<h2>Musik & Quellen</h2><div class="legal-section"><h3>Musik bei deinem Anbieter</h3><p>bias.fm hostet keine Musikdateien. Spotify, Apple Music, YouTube Music, MelOn und Bandcamp werden über externe Links geöffnet. Die Titel und Künstler im vorhandenen Katalog sind redaktioneller Referenzinhalt; Aufnahme-Credits sind noch nicht durchgehend unabhängig geprüft.</p></div><div class="legal-section"><h3>Release-Daten und Charts</h3><p>MusicBrainz-Einträge sind mit ihrer Originalquelle verlinkt. Künstler werden anhand geprüfter MusicBrainz-IDs zugeordnet. Last.fm-Tag-Charts zeigen das vom Dienst gelieferte Ranking, keine eigene Wochenchart. Öffentliche Redaktionsankündigungen tragen einen Quellenlink und werden durch die Redaktion gepflegt.</p></div>';
    }
  };root.biasLegalView=view;
})(window);
